export const AssetsMap = {
    sprites: [
        {name: 'back', url: './assets/game_background.jpg'},
        {name: 'zMan', url: './assets/zombies/zombie_man.png'},
        {name: 'zGirl', url: './assets/zombies/zombie_girl.png'},
        {name: 'zGranny', url: './assets/zombies/zombie_granny.png'},
        {name: 'zPoliceman', url: './assets/zombies/zombie_policeman.png'},
        {name: 'manWalk1', url: './assets/man/walking_1.png'},
        {name: 'manWalk2', url: './assets/man/walking_2.png'},
        {name: 'manWalk3', url: './assets/man/walking_3.png'},
        {name: 'manWalk8', url: './assets/man/walking_4.png'},
        {name: 'manWalk4', url: './assets/man/walking_5.png'},
        {name: 'manWalk5', url: './assets/man/walking_6.png'},
        {name: 'manWalk6', url: './assets/man/walking_7.png'},
        {name: 'manWalk7', url: './assets/man/walking_8.png'},
        {name: 'manStop', url: './assets/man/sprite_fornt.png'},
        {name: 'manZombie1', url: './assets/man/human_zombie_0.png'},
        {name: 'manZombie2', url: './assets/man/human_zombie_1.png'},
        {name: 'manZombie3', url: './assets/man/human_zombie_2.png'},
        {name: 'manZombie4', url: './assets/man/human_zombie_3.png'},
        {name: 'tree1', url: './assets/trees/tree_1.png'},
        {name: 'tree2', url: './assets/trees/tree_2.png'},
        {name: 'tree3', url: './assets/trees/tree_3.png'},
        {name: 'apple', url: './assets/profit/apple.png'},
        {name: 'box', url: './assets/profit/box.png'},
        {name: 'chocolate', url: './assets/profit/chocolate.png'},
        {name: 'firstAidKit', url: './assets/profit/first_aid_kit.png'},
        {name: 'money', url: './assets/profit/money.png'},
        {name: 'shotgun', url: './assets/profit/shotgun.png'},
        {name: 'logo', url: './assets/game_name.png'},
        {name: 'startScreen', url: './assets/popups/game_startscreen.png'},
        {name: 'popupLose', url: './assets/popups/popup_lose.png'},
        {name: 'popupNoMoney', url: './assets/popups/popup_no_money.png'},
        {name: 'popupWin', url: './assets/popups/popup_win.png'},
    ]
}